// train_skyjo_directional.mjs — train Skyjo solo-inspired policy with directional
// opponent features: previous-player supply and next-player feed denial.
import fs from 'fs';
import { Sim, skyjoFeatures } from './skyjo_sim.mjs';
import { makeRng } from './rng.mjs';

const BASE=JSON.parse(fs.readFileSync('training/skyjo_solo_params.json','utf8'));
const BASE4=BASE.n4, BASE6=BASE.n6;
const INIT4=[...BASE4,2,1,1,1,1];
const INIT6=[...BASE6,2,1,1,1,1];
const DIM=20;
function norm(P){const q=(Array.isArray(P)?P:(P.n4||P.n6)).slice();while(q.length<DIM)q.push(0);return q.slice(0,DIM);} 
function pickInit(obj,opps){if(Array.isArray(obj))return obj;return (opps.length>3?(obj.n6||obj.n4):(obj.n4||obj.n6));}
function baseParams(n){return norm(n<=4?BASE4:BASE6);} 
function hidden(p){return p.board.map((c,i)=>!c.r&&!c.c?i:-1).filter(i=>i>=0);}function revealed(p){return p.board.map((c,i)=>c.r&&!c.c?i:-1).filter(i=>i>=0);}function col(c){return[c,c+4,c+8];}function vis(p){return p.board.filter(c=>c.r&&!c.c).reduce((a,c)=>a+c.v,0);}function worst(p){const r=revealed(p);if(!r.length)return{idx:-1,val:-99};let idx=r[0],val=p.board[idx].v;for(const i of r)if(p.board[i].v>val){idx=i;val=p.board[i].v;}return{idx,val};}
function tripletGain(p,idx,val){const os=col(idx%4).filter(i=>i!==idx).map(i=>p.board[i]);if(os.every(c=>c.r&&!c.c&&c.v===val))return Math.max(-8,val+os[0].v+os[1].v);return os.filter(c=>c.r&&!c.c&&c.v===val).length;}
function endRisk(sim,me){if(sim.players.length<=1)return 0;const mine=vis(sim.players[me]);const best=Math.min(...sim.players.map((p,i)=>i===me?Infinity:vis(p)+hidden(p).length*2.5));return mine<=best?0:8;}
function prevSupply(sim,me,val){const n=sim.players.length;if(n<=1)return 0;const prev=sim.players[(me-1+n)%n];const w=worst(prev).val;let has=0;for(const i of revealed(prev))if(prev.board[i].v===val)has++;const high=Math.max(0,(val-4)/8);return (has?0.5*has:0)+(w===val?1:0)+high*(w>=val?0.5:0);} 
function nextDanger(sim,me){const n=sim.players.length;if(n<=1)return 0;const nx=sim.players[(me+1)%n];return Math.max(0,(20-vis(nx))/20)+(12-hidden(nx).length)/12;} 
function nextFeed(sim,me,val,P){const n=sim.players.length;if(n<=1)return 0;const nx=sim.players[(me+1)%n];let trip=0;for(let c=0;c<4;c++){const cs=col(c).map(i=>nx.board[i]);const rev=cs.filter(x=>x.r&&!x.c);if(rev.length>=2&&rev[0].v===rev[1].v&&rev[0].v===val)trip=1;}const w=worst(nx).val;const improve=Math.max(0,w-val)/12;return P[15]*trip+P[16]*improve+P[17]*nextDanger(sim,me)*(trip+improve>0?1:0);} 
function anchorValue(sim,me,idx,oldVal){const p=sim.players[me];const same=col(idx%4).filter(i=>i!==idx).map(i=>p.board[i]).filter(c=>c.r&&!c.c&&c.v===oldVal).length;return same*(1+prevSupply(sim,me,oldVal));}
function bestSwap(sim,me,val,P){const p=sim.players[me],cs=[...revealed(p),...hidden(p)],w=worst(p);let bi=cs[0]??0,bs=-1e9;for(const idx of cs){const c=p.board[idx];const old=c.r&&!c.c?c.v:5.2;const tg=tripletGain(p,idx,val);const complete=tg!==0&&Math.abs(tg)>1?tg:0;const pair=tg>0&&tg<=2?tg:0;const wouldEnd=hidden(p).length===1&&!c.r;const lowHidden=(!c.r&&val<=P[12]&&w.val<=P[13]&&!wouldEnd)?P[14]:0;const supply=P[18]*prevSupply(sim,me,val)*(pair>0?1:0);const preserve=(c.r&&!c.c)?P[19]*anchorValue(sim,me,idx,c.v):0;const score=(old-val)+P[4]*complete+P[5]*pair+ supply -(c.r?0:P[6])+lowHidden-preserve-(wouldEnd?endRisk(sim,me):0);if(score>bs){bs=score;bi=idx;}}return{idx:bi,score:bs};}
function revealChoice(sim,me,P,rng){const p=sim.players[me],h=hidden(p);let bi=h[0]??0,bs=-1e9;for(const idx of h){const rev=col(idx%4).map(i=>p.board[i]).filter(c=>c.r&&!c.c);const score=P[7]*(rev.length===0?1:0)+P[8]*rev.reduce((a,c)=>a+Math.max(0,c.v),0)-P[9]*(rev.length>=2&&rev[0].v===rev[1].v?1:0)+0.01*rng();if(score>bs){bs=score;bi=idx;}}return bi;}
function choose(sim,me,P,rng){const p=sim.players[me];if(sim.phase==='REVEAL')return{kind:'reveal',idx:revealChoice(sim,me,P,rng)};const h=hidden(p),w=worst(p);if(sim.ta===null){const dt=sim.discard[sim.discard.length-1];if(dt==null)return{kind:'draw'};const b=bestSwap(sim,me,dt,P);return(dt<=P[0]||b.score>=P[1]||(w.val-dt)>=P[2])?{kind:'take'}:{kind:'draw'};}const val=sim.drawn;if(sim.ta==='deck'){const b=bestSwap(sim,me,val,P);const feed=nextFeed(sim,me,val,P);if(val>=P[11]&&b.score+feed<P[1]+2&&h.length)return{kind:'discard'};return(b.score+feed>=P[3]||val<=P[0])?{kind:'swap',idx:b.idx}:{kind:'discard'};}if(sim.ta==='discard'){const b=bestSwap(sim,me,val,P);return{kind:'swap',idx:b.idx};}if(sim.ta==='must')return{kind:'reveal_after',idx:revealChoice(sim,me,P,rng)};}
function chooseThresh(sim,me,P,rng){const p=sim.players[me];if(sim.phase==='REVEAL'){const h=hidden(p);return{kind:'reveal',idx:h[Math.floor(rng()*h.length)]};}const f=skyjoFeatures(sim,me),h=hidden(p),wi=p.board.findIndex(c=>c.r&&!c.c&&c.v===f.worst);if(sim.ta===null){const dt=f.discardTop;return(dt!=null&&(dt<=P[0]||(f.worst-dt)>=P[1]))?{kind:'take'}:{kind:'draw'};}const d=sim.drawn;if(sim.ta==='deck'){if(wi>=0&&d<f.worst-P[2])return{kind:'swap',idx:wi};if(d<=P[3]&&h.length)return{kind:'swap',idx:h[Math.floor(rng()*h.length)]};return{kind:'discard'};}if(sim.ta==='discard'){if(wi>=0&&d<f.worst)return{kind:'swap',idx:wi};return{kind:'swap',idx:h.length?h[Math.floor(rng()*h.length)]:0};}if(sim.ta==='must')return{kind:'reveal_after',idx:h[Math.floor(rng()*h.length)]};}
function apply(sim,me,a){if(a.kind==='reveal')sim.reveal(me,a.idx);else if(a.kind==='take')sim.takeDiscard(me);else if(a.kind==='draw')sim.drawDeck(me);else if(a.kind==='swap')sim.swap(me,a.idx);else if(a.kind==='discard')sim.discardDrawn(me);else if(a.kind==='reveal_after')sim.revealAfter(me,a.idx);}function rotateArr(a,k){const n=a.length;return a.map((_,i)=>a[(i-k+n)%n]);}
function play(kinds,cs,P,seed){const sim=new Sim(kinds.length,{seed:`${seed}:d`});const rngs=kinds.map((_,i)=>makeRng(`${seed}:p:${i}`));let guard=0;while(guard++<10000){if(sim.phase==='REVEAL'){for(let i=0;i<kinds.length;i++)if(sim.players[i].rc<2){const h=hidden(sim.players[i]);sim.reveal(i,h[Math.floor(rngs[i]()*h.length)]);}if(sim.phase==='REVEAL')continue;}if(sim.phase==='ROUND_END'){if(sim.players.some(p=>p.total>=100))break;sim.nextRound();continue;}if(sim.phase==='GAME_OVER')break;if(sim.phase==='PLAY'||sim.phase==='FINAL'){const me=sim.cur,k=kinds[me];if(k==='candidate')apply(sim,me,choose(sim,me,P,rngs[me]));else if(k==='prod')apply(sim,me,choose(sim,me,baseParams(kinds.length),rngs[me]));else apply(sim,me,chooseThresh(sim,me,k==='easy'?[6,2,0,4]:[3,5,2,2],rngs[me]));}}const scores=sim.players.map(p=>p.total),mn=Math.min(...scores),winner=scores.findIndex(x=>x===mn),cand=scores[cs],best=Math.min(...scores.filter((_,i)=>i!==cs));return{win:winner===cs,margin:best-cand};}
function fitness(P,games,seed,opps){let w=0,m=0,t=0;const base=['candidate',...opps];for(let g=0;g<games;g++)for(let r=0;r<base.length;r++){const kinds=rotateArr(base,r),cs=kinds.indexOf('candidate'),res=play(kinds,cs,P,`${seed}:g${g}:r${r}`);if(res.win)w++;m+=res.margin;t++;}return w/t+0.0005*(m/t);}function randn(rng){let u=0,v=0;while(!u)u=rng();while(!v)v=rng();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v);}function clamp(P){const lim=[[-2,8],[-3,12],[-1,8],[-3,12],[-4,10],[-4,8],[0,5],[-4,10],[-2,4],[-4,6],[0,2],[3,12],[-2,3],[-2,10],[-6,10],[-5,10],[-5,10],[-5,10],[-5,10],[-5,10]];return P.map((x,i)=>Math.max(lim[i][0],Math.min(lim[i][1],x)));}
function train(){const seed=process.env.SEED||'skyjo-dir',rng=makeRng(seed),iters=Number(process.env.ITERS||12),pop=Number(process.env.POP||44),elite=Number(process.env.ELITE||10),games=Number(process.env.GAMES||60),opps=(process.env.OPPONENTS||'prod,medium,easy').split(',').filter(Boolean);let initObj=process.env.INIT_FILE?JSON.parse(fs.readFileSync(process.env.INIT_FILE,'utf8')):(opps.length>3?INIT6:INIT4),mean=norm(pickInit(initObj,opps)),std=Array(DIM).fill(Number(process.env.INIT_STD||0.7)),best=mean,bf=-1;console.log('directional opps='+opps.join(','));for(let it=0;it<iters;it++){const ss=[];for(let i=0;i<pop;i++){const P=clamp(mean.map((m,d)=>m+std[d]*randn(rng)));ss.push({P,f:fitness(P,games,`${seed}:it${it}:s${i}`,opps)});}ss.sort((a,b)=>b.f-a.f);const top=ss.slice(0,elite);if(top[0].f>bf){bf=top[0].f;best=top[0].P.slice();}for(let d=0;d<DIM;d++){const vals=top.map(x=>x.P[d]),mu=vals.reduce((a,b)=>a+b,0)/vals.length,sd=Math.sqrt(vals.reduce((a,b)=>a+(b-mu)*(b-mu),0)/vals.length)+0.05;mean[d]=mu;std[d]=Math.max(0.15,sd*0.86);}console.log(`iter ${it+1}/${iters} best=${top[0].f.toFixed(3)} mean=${(ss.reduce((a,b)=>a+b.f,0)/pop).toFixed(3)} P=[${mean.map(x=>x.toFixed(2)).join(',')}]`);}const out=process.env.OUT||'/tmp/skyjo_directional.json';const rounded=best.map(x=>+x.toFixed(3));fs.writeFileSync(out,JSON.stringify(rounded));console.log('BEST='+JSON.stringify(rounded));console.log('wrote',out);}train();
